/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AriaButton {
    }
}
declare global {
    interface HTMLAriaButtonElement extends Components.AriaButton, HTMLStencilElement {
    }
    var HTMLAriaButtonElement: {
        prototype: HTMLAriaButtonElement;
        new (): HTMLAriaButtonElement;
    };
    interface HTMLElementTagNameMap {
        "aria-button": HTMLAriaButtonElement;
    }
}
declare namespace LocalJSX {
    interface AriaButton {
    }
    interface IntrinsicElements {
        "aria-button": AriaButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "aria-button": LocalJSX.AriaButton & JSXBase.HTMLAttributes<HTMLAriaButtonElement>;
        }
    }
}
